services:
  mongo:
    image: mongo:7
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - appointment_mongo_data:/data/db
      - ./database/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  api:
    build:
      context: ..
      dockerfile: database/database/Dockerfile
    container_name: node_api
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    env_file:
      - ./database/.env

volumes:
  appointment_mongo_data:
